### ISSUE TITLE
Can't add as a Nativescript Library...

### ISSUE THREAD

**Issue by nedium** [msywensky/nativescript-phone#1]
When i try to add nativescript-phone to my app as a library, i type the new style
`tns plugin add nativescript-phone`
it fails and outputs:
`nativescript-phone is not a valid NativeScript plugin. Verify that the plugin pa
ckage.json file contains a nativescript key and try again.`

I think 
`"nativescript": {
    "platforms": {
      "android": "1.4.0",
      "ios": "1.4.0"
    }
  }`
part is missing in package.json

**Comment by rajarameshvarma** [comment]
I think this is no longer an issue. Can someone close this?

**Comment by nedium** [comment]
Confirmed, no longer an issue...
