### ISSUE TITLE
iOS 10 Xcode8 compatibility

### ISSUE THREAD

**Issue by DomGaud** [msywensky/nativescript-phone#14]
With the release of iOS 10 and Xcode 8 the dial function doesn't work.
There have been some changes in the iOS sdk from using methods to properties.
So you will need to change `UIApplication.sharedApplication().canOpenURL()` and `openURL()` from using the old method to using the properties.

I simply changed from using `UIApplication.sharedApplication()` to `utils.ios.getter(UIApplication, UIApplication.sharedApplication)` in the [index.ios.js](https://github.com/msywensky/nativescript-phone/blob/master/index.ios.js) file and the function now works. Not sure if this is a proper fix, but thought it might lead you in the right direction for a permanent resolve.

**Comment by thomasmoon** [comment]
+1  Thanks for the nice plugin!

**Comment by stefalda** [comment]
Another solution is to change the code in this way to fix the problem...

`var a = typeof UIApplication.sharedApplication === 'function'? UIApplication.sharedApplication() : UIApplication.sharedApplication;
`

Anyway I think this PR is quite urgent because otherwise the plugin is broken on IOS10
