### ISSUE TITLE
doesnot work in ios with ns 2.3.0.

### ISSUE THREAD

**Issue by sowrabhbs** [msywensky/nativescript-phone#19]
ends with error   Can't find variable: utils.
I am working with angular2 and typescript.

**Comment by bradmartin** [comment]
I'll add the fix and push, I should've caught the require on that 😄

**Comment by sowrabhbs** [comment]
Ok thanks:)

**Comment by bradmartin** [comment]
Try it out and let me know, should work fine now.

**Comment by bradmartin** [comment]
I'll test this in a few minutes. I thought I tested but I might have not
bumped the version during testing. What's the error you get?

**Comment by sowrabhbs** [comment]
its working Thanks.
