### ISSUE TITLE
Gettting {response : cancelled} Event after message was sent successfully

### ISSUE THREAD

**Issue by prantikv** [msywensky/nativescript-phone#22]
I am sending SMSes using TNS and ng2 on an Android 6.0 device.

Here is the code

```
permissions.requestPermission(android.Manifest.permission.SEND_SMS, "I need these permissions because I'm cool")
        .then(function() {
          TNSPhone.sms(['987654321'], "Text till your fingers bleed")
                .then((args:any) => {
                    console.log(JSON.stringify(args));
                }, (err) => {
                    console.log('Error: ' + err);
                });
        .catch(function() {
            console.log("Uh oh, no permissions - plan B time!");
        });
```

The above code is executed on the tap event of a button. So when the button is tapped, the native SMS app opens up, where the number and text message is pre-filled. I just hit the send button and the message is sent.

All good till now.

But I do not get any output in the success callback.

Moreover, after the message has been sent. I close the native SMS app, which takes me back to my app. i get the following.

`JS: {"response":"cancelled"}`

This means that in the promise the success callback is executed.

Is there a way to get the success in the args response of the success callback.

**Comment by msangapu** [comment]
+1 looks like it's capturing the event from pressing the back button from the native SMS app...

**Comment by Adam95** [comment]
+1 any progress on this? I got to the same situation.

**Comment by bradmartin** [comment]
I believe this will always be the result for android currently. 

The plugin would need to be improved and have a [ContentObserver](https://developer.android.com/reference/android/database/ContentObserver.html) added to monitor and track the message if it is sent. The result will always be `cancelled` because the SMS application has been closed (cancelled).

**Comment by prashantnirgun** [comment]
does anyone find or fix this issue ?

**Comment by mrpaaske** [comment]
Also looking for a fix for this issue.

**Comment by fpaaske** [comment]
This issue was solved for us with the new event based method in v3.x, ref #51
