### ISSUE TITLE
[Android] ignores default SMS application

### ISSUE THREAD

**Issue by lukashlobil** [msywensky/nativescript-phone#24]
Hi, first of all, thanks for awesome plugin.

I have an issue on Android. The plugin opens the preinstalled SMS application, but I have selected Hangouts as default SMS app. 

This wouldn't matter as much, but since this factory default SMS app is "disabled", it won't let me send the message, unless I change it to the default one. 

Hopefully screenshots will make it easier to understand.

Prompt for default app change:
![screenshot_20170112-164918](https://cloud.githubusercontent.com/assets/9610365/21896618/55e058d2-d8e7-11e6-9a41-099bc1d36af2.png)

Disabled send button:
![screenshot_20170112-164927](https://cloud.githubusercontent.com/assets/9610365/21896611/4abbca68-d8e7-11e6-83a1-1877f93d5e0d.png)

**Comment by msywensky** [comment]
Hi @lukashlobil.  The js code does not specify the client, but instead makes a standard sms call using the sms url:  
intent.setData(android.net.Uri.parse("sms:" + smsNum.join(";")));  

If i had to guess, I would chalk this up to a configuration issue on your phone.
