### ISSUE TITLE
Accessing own phone number

### ISSUE THREAD

**Issue by ickata** [msywensky/nativescript-phone#28]
Hi,

Does this plugin allow reading own phone #? On iOS phone # is available in [phone/contacts](https://tunesgo.wondershare.com/images/en/iphone-connect/my-number-2.jpg) which makes me think that it can be accessed (not sure for Android). I would like to get user's phone # (asking the user for permission is OK) and populate a textfield with it.

**Comment by msywensky** [comment]
No, accessing the device phone number is not part of this plugin.
