### ISSUE TITLE
Shipped ES6 code breaks --uglify build

### ISSUE THREAD

**Issue by jogboms** [msywensky/nativescript-phone#30]
It appears using es6's optional function parameter breaks the webpack's --uglify build.
I tracked it down to this function declaration.

`function dial(telNum, prompt = true)`
---------
`tns --version  3.1.1`
`tns-core-modules 3.1.0`
`tns-android 3.1.1`
`nativescript-phone 1.3.0`

**Comment by jogboms** [comment]
It seems to have been addressed by PR https://github.com/msywensky/nativescript-phone/pull/29.

cc @bradmartin

**Comment by bradmartin** [comment]
1.3.1 published with fix
