### ISSUE TITLE
Android fails if number doesn't contain "#"

### ISSUE THREAD

**Issue by chriswill412** [msywensky/nativescript-phone#31]
Current Setup
-Nativescript 3.4.1
-TNS Android 3.4.1 
-Angular 5.2.1
-webpack, snapshot, uglified, not

Line 28 in the index.android.js fails with the following error 
"TypeError: telNum.replace is not a function"

**Comment by bl1nkr** [comment]
We have the same issue above

**Comment by checkpals** [comment]
On calling the dial function, pass the phone number as string. 
This should fix the  issue
import * as CCAPhone from 'nativescript-phone';

public MakeACall(arg) {
      try {
        CCAPhone.dial(arg.toString(), true);
      } catch (error) {
        console.log(error);
      }
    }

**Comment by bradmartin** [comment]
as @checkpals said, the number should be type `string` so the `replace` function will work.

The typings have it marked as `string` https://github.com/msywensky/nativescript-phone/blob/master/src/index.d.ts#L7 and I believe the README also is correct. 

Hope that helps.
