### ISSUE TITLE
Problem when dial within Observable.subscribe

### ISSUE THREAD

**Issue by RadouaneRoufid** [msywensky/nativescript-phone#32]
I have an angular Directive to make phone dial. My code is as following : 

```
@HostListener('tap')
    callPhone() {
        this.userService.getUserPhone(this.userUid)
            .subscribe(p => {
                TNSPhone.dial(String(p), true);
            });
    }
```

This code does not work and an JS: [object Object] is printed on the console. 

However, the code below works

```
@HostListener('tap')
    callPhone() {
                TNSPhone.dial(String(p), true);
    }
```

How can I deal with that ?

**Comment by carlosen14** [comment]
how did you solve it? it happens the same with primises
