### ISSUE TITLE
SMS works but phone calls doesn't on android

### ISSUE THREAD

**Issue by Xsmael** [msywensky/nativescript-phone#33]
SMS works but phone calls doesn't on android, when setting the second parameter of the call function to `false`
```
var phone = require( "nativescript-phone" );
phone.dial("212-555-1234",false);
```

**Comment by bradmartin** [comment]
This will work, but you will have to request the call permission on android to bypass the call prompt.

See the demo [here](https://github.com/msywensky/nativescript-phone/blob/master/demo/app/main-page.js#L24) and look also at the demo permission handling in that file. Without the permission, android will not allow an app to make a call without the phone prompt. 

Hope that helps 👍
