### ISSUE TITLE
"Cannot send message text" error on iOS simulator

### ISSUE THREAD

**Issue by sandoche** [msywensky/nativescript-phone#36]
Hi,

The simulator sends me this error on iOS, is it normal?
The simulator does have a SMS app.

![photo_2019-01-26_18-17-53](https://user-images.githubusercontent.com/3635348/51790539-02aa3c00-2197-11e9-9de7-f0faccb3795e.jpg)

What can I do?

**Comment by bradmartin** [comment]
Nothing can be done on the simulator with SMS or push notifications on iOS. You need a real iOS device to test.

https://stackoverflow.com/a/9012468/1893557

**Comment by sandoche** [comment]
Thanks it works on a device!
