### ISSUE TITLE
Dial not working on iOS with TNS v5.3.1

### ISSUE THREAD

**Issue by HugoAntares** [msywensky/nativescript-phone#37]
# Dial not working on iOS with TNS v5.3.1

```javascript
import * as phone from 'nativescript-phone';
phone.dial(String(this.data.phone), true);
```
Nothing happens and no error thrown. My `Info.plist`:
```plist
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>tel</string>
    <string>telprompt</string>
</array>
```

## Versions

* TNS cli 5.3.0
* package.json tns-ios 5.3.1
* nativescript-phone 1.4.0

**Comment by ChrisJohns-me** [comment]
If you're like me and hitting your head for a while over this one and using the Apple SimulatorApp, keep in mind that **the Simulator does not contain a SIM card and will not open `tel` or `telprompt` links** (which is what nativescript-phone is using).

Try using it on a real iOS device with calling capabilities.

**Comment by dmserrano** [comment]
I am having issues with this as well.

Current versions:
- TNS cli 5.3.0
- tns-ios v5.3.1
- nativescript-phone 1.4.0

It is throwing this error in the device logs when passing a phone number into the `dial` method:

`-canOpenURL: failed for URL: "(null)" - error: "Invalid input URL"`

The phone number I am passing in is in this format `(111) 111-1111`, which was working with a previous version. After changing the format to `111-111-1111` the error is not thrown and I am prompted with the dial window. I running this on a real iOS device.

**Comment by salvadorcoronel** [comment]
I have the same problem.

Versions:
- TNS cli 5.4.2
- tns-core-modules 5.4.3
- tns-ios 5.4.2
- nativescript-phone 1.4.0

I see this error in console (I am testing from real iOS device):
`-canOpenURL: failed for URL: "(null)" - error: "Invalid input URL"`

The phone number is: 013119898

**Comment by KonstantinObuhov** [comment]
+1

**Comment by msajjid** [comment]
Those who are still having issue in iPhone devices, create this utility specifically for iPhone platform.

```
import { Utils } from "@nativescript/core";
import { dataSerialize } from "@nativescript/core/utils";

export function dialIOS(phoneNumber: string): Promise<boolean> {
  return new Promise((resolve) => {
    const formatted = phoneNumber.startsWith("+")
      ? phoneNumber
      : `+${phoneNumber.replace(/^0+/, "")}`;

    Utils.executeOnMainThread(() => {
      const app = UIApplication.sharedApplication;
      const url = NSURL.URLWithString(`tel:${formatted.trim()}`);

      if (!url || !app.canOpenURL(url)) {
        return resolve(false);
      }

      app.openURLOptionsCompletionHandler(
        url,
        dataSerialize({}),
        (success: boolean) => resolve(success)
      );
    });
  });
}
```
