### ISSUE TITLE
Getting "No v4 support" and permission issue in Nativescript 6 version

### ISSUE THREAD

**Issue by adilsaeed31** [msywensky/nativescript-phone#41]
Hi I am using this plugin in nativescript v6 but when I called the method to call on number I am getting this error

```
JS: No v4 support
JS: No v4 support
JS: Error: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxxxxxxxxx cmp=com.android.server.telecom/.components.UserCallActivity } from ProcessRecord{75bfe7d 17305:org.nativescript.phcc/u0a482} (pid=17305, uid=10482) with revoked permission android.permission.CALL_PHONE
JS:     android.os.Parcel.createException(Parcel.java:1950)
JS:     android.os.Parcel.readException(Parcel.java:1918)
JS:     android.os.Parcel.readException(Parcel.java:1868)
JS:     android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3668)
JS:     android.app.Instrumentation.execStartActivity(Instrumentation.java:1856)
JS:     android.app.Activity.startActivityForResult(Activity.java:4605)
JS:     androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
JS:     android.app.Activity.startActivityForResult(Activity.java:4563)
JS:     androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
JS:     android.app.Activity.startActivity(Activity.j...

```

I have already added the permission to ANDROID in AndroidManifest.xml file and IOS in info.plist file

**Comment by adilsaeed31** [comment]
Is someone maintaing this repository?

**Comment by bradmartin** [comment]
I believe you need to do a runtime check for that permission on Android. 

Simplest option ATM: use `nativescript-permissions` and do the runtime check.

**Comment by chimmelb** [comment]
I ran into this in a round-about way from nativescript-camera. Same symptoms as here. I just uninstalled, reinstalled nativescript-phone and this is my `npm ls --depth=2`

```
├─┬ nativescript-phone@1.4.0
│ └── nativescript-permissions@1.2.3
```

Talking to nathanael on slack channel, he noted that nativescript-permissions should be 1.3.6, which is in this repos src/package.json but does not appear after an npm install for me. Is everything good on NPM?

**Comment by chimmelb** [comment]
side note, I installed `nativescript-permissions` local to my project (1.3.6 is the latest) and my issue went away. Unsure how nativescript-phone's old version of nativescript-permissions was affecting my app's camera through nativescript-camera (perhaps something with Android jars/bindings?) but hopefully these comments help get things sorted.

**Comment by adilsaeed31** [comment]
@chimmelb thank you so much for your kind reply and concern here, my issue is fixed I have added the nativescript-permissions plugin separately and asking permissions through this plugin and then using your plugin for calling it's working perfectly now. Thank you.

**Comment by chimmelb** [comment]
@msywensky Just wanted to bring this Issue to your attention in case the NPM package is off. See my previous comment: when installing `nativescript-phone` 1.4.0 it gets `nativescript-permissions` 1.2.3. The last modified package.json on master says 1.3.6, but something is off (at least in this Issue)

**Comment by adilsaeed31** [comment]
It's already fix by adding nativescript-permissions plugin separately
