### ISSUE TITLE
Error : utils.ios.getter() is deprecated; use the respective native property instead

### ISSUE THREAD

**Issue by sanghyunj5958** [msywensky/nativescript-phone#45]
Hello,

I'm getting this error after I update to Nativescript 6.0. and I'm using Angular.

Please update this plug-in

Thank you

file:///node_modules/tns-core-modules/utils/utils.js:48:0 utils.ios.getter() is deprecated; use the respective native property instead

**Comment by mflor35** [comment]
I believe this has been fixed in the lastest PRs, but I don't think there's has been a release cut

**Comment by nulele** [comment]
Hi, any news? I'm facing the same problem here :(

**Comment by bradmartin** [comment]
1.4.1 published with master (and the fix here)
