### ISSUE TITLE
Is that possible to not pop up the android native send message dialog but directly send message in background?

### ISSUE THREAD

**Issue by hi-hai** [msywensky/nativescript-phone#46]
Currently when called nativescript-phone to send text, it just switched to Android send text message page and wait for user to click send button. Is that possible to bypass this extra step and directly send message?

**Comment by stefalda** [comment]
As far as I know that's not possible unless your app is released outside the Play Store... technically it's feasible by calling some native Android API.

**Comment by bradmartin** [comment]
You can, it's a very heavy process. Need permissions to be an SMS app, use the SmsManager https://developer.android.com/reference/android/telephony/SmsManager, write a service I believe to handle all the necessary events.
