### ISSUE TITLE
Crash on xcode simulator

### ISSUE THREAD

**Issue by geraldapeoples** [msywensky/nativescript-phone#48]
When I run my app on a real phone it works perfectly. When I run it on the simulator it crashes every time.

2020-03-11 12:21:04.970916+0000 rrmobile[17954:234015] *** JavaScript call stack:
(
	0   extend@[native code]
	1   ../node_modules/nativescript-phone/index.js@file:///app/vendor.js:165556:67
	2   __webpack_require__@file:///app/runtime.js:75:34
	3   ./app/shared/alert-detail/alert-detail.component.ts@file:///app/1.js:144:96
	4   __webpack_require__@file:///app/runtime.js:75:34
	5   ./app/shared/alert-detail/alert-detail.module.ts@file:///app/1.js:602:100
	6   __webpack_require__@file:///app/runtime.js:75:34
	7   ./app/pages/alerts/alerts.module.ts@file:///app/12.js:58:121
	8   __webpack_require__@file:///app/runtime.js:75:34
	9   __webpack_require__@[native code]
	10  onInvoke@file:///app/vendor.js:64364:39
	11  @file:///app/vendor.js:90372:49
	12  @file:///app/vendor.js:91117:37
	13  onInvokeTask@file:///app/vendor.js:64355:43
	14  @file:///app/vendor.js:90422:57
	15  drainMicroTaskQueue@file:///app/vendor.js:90829:42
	16  promiseReactionJob@:1:11
	17  UIApplicationMain@[native code]
	18  run@file:///app/vendor.js:92561:26
	19  @file:///app/vendor.js:86830:26
	20  @file:///app/vendor.js:86731:38
	21  @file:///app/vendor.js:86711:26
	22  ./main.ts@file:///app/bundle.js:2978:116
	23  __webpack_require__@file:///app/runtime.js:75:34
	24  checkDeferredModules@file:///app/runtime.js:44:42
	25  webpackJsonpCallback@file:///app/runtime.js:31:39
	26  anonymous@file:///app/bundle.js:2:61
	27  evaluate@[native code]
	28  moduleEvaluation@:1:11
	29  @:2:1
	30  asyncFunctionResume@:1:11
	31  @:24:9
	32  promiseReactionJob@:1:11
)
2020-03-11 12:21:04.971369+0000 rrmobile[17954:234015] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Class "MFMessageComposeViewController" referenced by type encoding not found at runtime.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   NativeScript                        0x00000001092d7280 _ZN12NativeScript11TypeFactory9parseTypeEPNS_12GlobalObjectERPKN8Metadata12TypeEncodingEb + 6016
	3   NativeScript                        0x00000001092d7d79 _ZN12NativeScript11TypeFactory10parseTypesEPNS_12GlobalObjectERPKN8Metadata12TypeEncodingEib + 329
	4   NativeScript                        0x00000001092bcb42 _ZN12NativeScript17ObjCMethodWrapper14finishCreationERN3JSC2VMEPNS_12GlobalObjectEN3WTF7HashSetIPKN8Metadata10MemberMetaENS6_7PtrHashISB_EENS6_10HashTraitsISB_EEEE + 594
	5   NativeScript                        0x00000001092a631a _ZN12NativeScript17ObjCMethodWrapper6createERN3JSC2VMEPNS_12GlobalObjectEPNS1_9StructureEN3WTF7HashSetIPKN8Metadata10MemberMetaENS8_7PtrHashISD_EENS8_10HashTraitsISD_EEEE + 362
	6   NativeScript                        0x00000001092bee68 _ZN12NativeScript23overrideObjcMethodCallsEPN3JSC9ExecStateEPNS0_8JSObjectENS0_12PropertyNameEPNS0_6JSCellEPKN8Metadata13BaseClassMetaENS8_10MemberTypeEP10objc_classRKN3WTF6VectorIPKNS8_12ProtocolMetaELm0ENSF_15CrashOnOverflowELm16EEE + 1272
	7   NativeScript                        0x00000001092ac1c1 _ZN12NativeScript16ObjCClassBuilder17addInstanceMethodEPN3JSC9ExecStateERKNS1_10IdentifierEPNS1_6JSCellE + 369
	8   NativeScript                        0x00000001092b21d0 _ZN12NativeScript16ObjCClassBuilder18addInstanceMembersEPN3JSC9ExecStateEPNS1_8JSObjectENS1_7JSValueE + 9264
	9   NativeScript                        0x00000001092b6474 _ZN12NativeScript18ObjCExtendFunctionEPN3JSC9ExecStateE + 6148
	10  ???                                 0x00002bc37b20116b 0x0 + 48118584316267
	11  NativeScript                        0x0000000109cb810f llint_entry + 93226
	12  ???                                 0x00002bc37b211f37 0x0 + 48118584385335
	13  NativeScript                        0x0000000109cb810f llint_entry + 93226
	14  ???                                 0x00002bc37b211f37 0x0 + 48118584385335
	15  NativeScript                        0x0000000109cb810f llint_entry + 93226
	16  ???                                 0x00002bc37b211f37 0x0 + 48118584385335
	17  NativeScript                        0x0000000109cb810f llint_entry + 93226
	18  ???                                 0x00002bc37b211f37 0x0 + 48118584385335
	19  NativeScript                        0x0000000109ca133b vmEntryToJavaScript + 200
	20  NativeScript                        0x00000001093729dc _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 460
	21  NativeScript                        0x0000000109b3eabb _ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 59
	22  NativeScript                        0x00000001099844f7 _ZN3JSC17boundFunctionCallEPNS_9ExecStateE + 695
	23  ???                                 0x00002bc37b20116b 0x0 + 48118584316267
	24  ???                                 0x00002bc37b658776 0x0 + 48118588868470
	25  ???                                 0x00002bc37b69fce2 0x0 + 48118589160674
	26  ???                                 0x00002bc37b782628 0x0 + 48118590088744
	27  ???                                 0x00002bc37b72fcf7 0x0 + 48118589750519
	28  ???                                 0x00002bc37b6ed338 0x0 + 48118589477688
	29  ???                                 0x00002bc37b9cc095 0x0 + 48118592487573
	30  ???                                 0x00002bc37b207712 0x0 + 48118584342290
	31  NativeScript                        0x0000000109ca133b vmEntryToJavaScript + 200
	32  NativeScript                        0x00000001093729dc _ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 460
	33  NativeScript                        0x0000000109b3ece4 _ZN3JSC12profiledCallEPNS_9ExecStateENS_15ProfilingReasonENS_7JSValueENS_8CallTypeERKNS_8CallDataES3_RKNS_7ArgListE + 196
	34  NativeScript                        0x00000001099e282c _ZN3JSC11JSMicrotask3runEPNS_9ExecStateE + 492
	35  NativeScript                        0x000000010924a6b2 _ZN12NativeScript12GlobalObject15drainMicrotasksEv + 178
	36  NativeScript                        0x00000001092477a1 _ZN12NativeScriptL33microtaskRunLoopSourcePerformWorkEPv + 33
	37  CoreFoundation                      0x00007fff23bb2221 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	38  CoreFoundation                      0x00007fff23bb214c __CFRunLoopDoSource0 + 76
	39  CoreFoundation                      0x00007fff23bb1924 __CFRunLoopDoSources0 + 180
	40  CoreFoundation                      0x00007fff23bac62f __CFRunLoopRun + 1263
	41  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	42  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	43  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	44  NativeScript                        0x0000000109cc2c1d ffi_call_unix64 + 85
	45  ???                                 0x0000000113645020 0x0 + 4620308512
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by bradmartin** [comment]
Don't believe iOS allows this API to work on simulator. If it works on real device that's all that matters anyway. Same with notifications, was not possible to do notifications on simulators previously (not sure if still same) and bluetooth. Very limiting IMO for a lot of apps but not much we can do :)

**Comment by SingleMalted** [comment]
Just an update on this... 

It seems that simply importing this module `import * as TNSPhone from "nativescript-phone"` crashes the iOS simulator without even calling a method.

**Comment by datanotion** [comment]
Hey @bradmartin - this is also affecting us.  Any way to take a peek and see if it's able to just be imported without crashing on the simulator?  We don't need the API to function on the sim of course, but not being able to run the app `at all` is painful.  If not, is there an alternative you know of?

**Comment by bradmartin** [comment]
I'll take a look at it now actually and let ya know 👍

**Comment by bradmartin** [comment]
It's not crashing the simulator for me. 
<img width="1352" alt="nocrash" src="https://user-images.githubusercontent.com/6006148/82682891-9b2ec000-9c15-11ea-8381-6e986eb52bd0.png">

I thought maybe it was a `tsc` issue when importing all so I made a demo app and added the plugin, imported * and even call the `sms` method on the button tap... no crash on simulator.

**Comment by SingleMalted** [comment]
Hey @bradmartin - Thanks for getting back to us.

Looks like your plugin isn't the sole issue here, so we're looking into possible conflicting packages. We'll let you know what we find.

Thanks for all of your hard work. 🍻

**Comment by Villarrealized** [comment]
I have this same issue on iOS simulator 12.4. When I run on a simulator iOS 13 or newer this crash does not happen. Any ideas on why it crashes in iOS automatically? @SingleMalted @datanotion. Did you ever figure this out?

**Comment by SingleMalted** [comment]
@Villarrealized We never figured it out. We just worked around it as it is only used in one small part of our app.

**Comment by SmailHammour** [comment]
I had the same crash on my physical device;

```
Hang detected: 0.70s (always-on hang reporting)
*** JavaScript call stack:
(
0   extend@[native code]
1   ../node_modules/nativescript-phone/index.js@file: node_modules/nativescript-phone/index.ios.js:6:0
2   __webpack_require__@file: src/webpack/bootstrap:74:0
3   ./app/presentation/pages/connect/connect-to-people/contact-group/contact/contact.component.ts@file: src/app/presentation/pages/connect/connect-to-people/contact-group/contact/contact.component.ts:1:0
4   __webpack_require__@file: src/webpack/bootstrap:74:0
5   ./app/presentation/pages/connect/connect-to-people/connect-to-people-form/connect-to-people-form.component.ts@file: src/app/presentation/pages/connect/connect-to-people/connect-to-people-form/connect-to-people-form.component.ts:1:0
6   __webpack_require__@file: src/webpack/bootstrap:74:0
7   ./app/presentation/pages/connect/connect-to-people/connect-to-people.module.ts@file: src/app/presentation/pages/connect/connect-to-people/connect-to-people.module.ts:1:0
8   __webpack_require__@file: src/webpack/bootstrap:74:0
9   __webpack_require__@[native code]
10  onInvoke@file: node_modules/@angular/core/fesm2015/core.js:27486:0
11  @file: node_modules/@nativescript/zone-js/zone-nativescript.js:138:0
12  @file: node_modules/@nativescript/zone-js/zone-nativescript.js:883:0
13  onInvokeTask@file: node_modules/@angular/core/fesm2015/core.js:27474:0
14  @file: node_modules/@nativescript/zone-js/zone-nativescript.js:188:0
15  drainMicroTaskQueue@file: node_modules/@nativescript/zone-js/zone-nativescript.js:595:0
16  promiseRe<\M-b\M^@\M-&>
)
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Class "MFMessageComposeViewController" referenced by type encoding not found at runtime.'
*** First throw call stack:
(0x1ae3f8878 0x1c294ec50 0x103e4c934 0x103e4d090 0x103e34498 0x103e1fe50 0x103e362d8 0x103e2542c 0x103e2a83c 0x103e2d628 0x10496f7cc 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10494e5e8 0x103efce48 0x1046140d0 0x10496f7cc 0x10496ce80 0x10496ce80 0x10496ce80 0x10496ce80 0x10496ce80 0x10496ce80 0x10496ce80 0x10494e5e8 0x103efce48 0x1047a0e50 0x10466ad9c 0x103dcf304 0x103dcc9b4 0x1ae37476c 0x1ae374668 0x1ae373960 0x1ae36da8c 0x1ae36d21c 0x1c53ec784 0x1b0da6200 0x1b0daba74 0x1049a4044 0x1049a2ae8 0x1049a2648 0x103dc13d8 0x10496fb10 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496cf28 0x10496ce80 0x10496cf28 0x10494e5e8 0x103efce48 0x1047a0cb4 0x103dd98f4 0x1046719d0 0x10496f7cc 0x10496cf28 0x10496cf28 0x10496cf28 0x10496ce80 0x1<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x103e47018 sig_handler(int)
2   0x1f780a290 <redacted>
3   0x1f780fb40 pthread_kill
4   0x1b771cb74 abort
5   0x1c2a54cf8 <redacted>
6   0x1c2a45e4c <redacted>
7   0x1c294ef64 <redacted>
8   0x1c2a540e0 <redacted>
9   0x1c2a56eb0 __cxa_get_exception_ptr
10  0x1c2a56e5c <redacted>
11  0x1c294ed7c <redacted>
12  0x103e4c934 NativeScript::TypeFactory::parseType(NativeScript::GlobalObject*, Metadata::TypeEncoding const*&, bool)
13  0x103e4d090 NativeScript::TypeFactory::parseTypes(NativeScript::GlobalObject*, Metadata::TypeEncoding const*&, int, bool)
14  0x103e34498 NativeScript::ObjCMethodWrapper::finishCreation(JSC::VM&, NativeScript::GlobalObject*, WTF::HashSet<Metadata::MemberMeta const*, WTF::PtrHash<Metadata::MemberMeta const*>, WTF::HashTraits<Metadata::MemberMeta const*> >)
15  0x103e1fe50 NativeScript::ObjCMethodWrapper::create(JSC::VM&, NativeScript::GlobalObject*, JSC::Structure*, WTF::HashSet<Metadata::MemberMeta const*, WTF::PtrHash<Metadata::MemberMeta const*>, WTF::HashTraits<Metadata::MemberMeta const*> >)
16  0x103e362d8 NativeScript::overrideObjcMethodCalls(JSC::ExecState*, JSC::JSObject*, JSC::PropertyName, JSC::JSCell*, Metadata::BaseClassMeta const*, Metadata::MemberType, objc_class*, WTF::Vector<Metadata::ProtocolMeta const*, 0ul, WTF::CrashOnOverflow, 16ul> const&)
17  0x103e2542c NativeScript::ObjCClassBuilder::addInstanceMethod(JSC::ExecState*, JSC::Identifier const&, JSC::JSCell*)
18  0x103e2a83c NativeScript::ObjCClassBuilder::addInstanceMembers(JSC::ExecState*, JSC::JSObject*, JSC::JSValue)
19  0x103e2d628 NativeScript::ObjCExtendFunction(JSC::ExecState*)
20  0x10496f7cc llint_entry
21  0x10496cf28 llint_entry
22  0x10496cf28 llint_entry
23  0x10496cf28 llint_entry
24  0x10496cf28 llint_entry
25  0x10496cf28 llint_entry
26  0x10496cf28 llint_entry
27  0x10496cf28 llint_entry
28  0x10496cf28 llint_entry
29  0x10494e5e8 vmEntryToJavaScript
30  0x103efce48 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
31  0x1046140d0 JSC::boundFunctionCall(JSC::ExecState*)
JS Stack:
extend([native code])
at ../node_modules/nativescript-phone/index.js(file: node_modules/nativescript-phone/index.ios.js:6:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./app/presentation/pages/connect/connect-to-people/contact-group/contact/contact.component.ts(file: src/app/presentation/pages/connect/connect-to-people/contact-group/contact/contact.component.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./app/presentation/pages/connect/connect-to-people/connect-to-people-form/connect-to-people-form.component.ts(file: src/app/presentation/pages/connect/connect-to-people/connect-to-people-form/connect-to-people-form.component.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at ./app/presentation/pages/connect/connect-to-people/connect-to-people.module.ts(file: src/app/presentation/pages/connect/connect-to-people/connect-to-people.module.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:74:0)
at __webpack_require__([native code])
at onInvoke(file: node_modules/@angular/core/fesm2015/core.js:27486:0)
at file: node_modules/@nativescript/zone-js/zone-nativescript.js:138:0
at file: node_modules/@nativescript/zone-js/zone-nativescript.js:883:0
at onInvokeTask(file: node_modules/@angular/core/fesm2015/core.js:27474:0)
at file: node_modules/@nativescript/zone-js/zone-nativescript.js:188:0
at drainMicroTaskQueue(file: node_modules/@nativescript/zone-js/zone-nativescript.js:595:0)
at promiseReactionJob
at UIApplicationM<\M-b\M^@\M-&>
```
