### ISSUE TITLE
Handle USSD with more than one pound sign (#)

### ISSUE THREAD

**Issue by fpaaske** [msywensky/nativescript-phone#56]
If we try to dial a USSD code, #99#, the last # is not showing in the dialer. However, for *99#, it is shown.
I suspect it's this line that should have encoded all #, not just the first it finds.

https://github.com/msywensky/nativescript-phone/blob/6a698e296fb8f56f08f7832442a553fe4f53c4a2/src/index.android.js#L21

**Comment by fpaaske** [comment]
@msywensky, did you have time to look at this?

**Comment by msywensky** [comment]
Hi @fpaaske.  I'll be honest... it has been a couple years since I did anything with NativeScript other than review and merge pull requests on this repo.  If you submit a pull request, myself or @bradmartin will merge it.

**Comment by fpaaske** [comment]
@msywensky @bradmartin I made this fix, so if you could test, merge and release it, I'd be super happy :)

**Comment by fpaaske** [comment]
Thank you!
