### ISSUE TITLE
WARNING: The file: ...../node_modules/nativescript-phone/platforms/android/AndroidManifest.xml

### ISSUE THREAD

**Issue by leocaseiro** [msywensky/nativescript-phone#7]
Hi first of all thank you for this awesome plugin, I've just got into deploy and I receive this warning:

> WARNING: The file: ..../node_modules/nativescript-phone/platforms/android/AndroidManifest.xml is depricated, you can read more about what will be the expected plugin structure here: https://www.nativescript.org/blog/migrating-n-android-plugins-from-version-1.7-to-2.0

It might me nice to swap the structure.

**Comment by zeeshanjan82** [comment]
@leocaseiro for me the plugin does not work, I am not able to call on a number, everything seems fine there is no error thrown but still the call is not initiated. I get this warning in the console, is it because of this warning.

**Comment by leocaseiro** [comment]
It seems the [AndroidManifest.xml](https://github.com/msywensky/nativescript-phone/blob/master/platforms/android/AndroidManifest.xml) was added in the correct structure. 

Closing this issue.
